{% set name = "jupyterlab_commands" %}
{% set version = "0.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 210c851ee4c7439ac593018542c599a9085e459bc1bc1fb3ea92d2a9bf3e11ff

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.7
    - pip
    - nodejs >=16
    - yarn
    - hatchling
    - hatch-jupyter-builder
    - jupyterlab >=4,<5
  run:
    - python >=3.7
    - jupyterlab >=4,<5

test:
  imports:
    - jupyterlab_commands

about:
  home: http://github.com/timkpaine/jupyterlab_commands
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Arbitrary python commands for notebooks in JupyterLab

  description: |
    Arbitrary python commands for notebooks in JupyterLab
  dev_url: https://github.com/timkpaine/jupyterlab_commands

extra:
  recipe-maintainers:
    - timkpaine
