{% set name = "jupyterlab_commands" %}
{% set version = "0.2.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 9fc01f7ab0bafe889be8db9d12faf7428199fd29c90ff0bdff94f2f1090504c2

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.7
    - pip
    - nodejs
    - jupyter-packaging
  run:
    - python >=3.7
    - jupyterlab >=1.0.0
    - notebook >=6.0.3

test:
  imports:
    - jupyterlab_commands

about:
  home: http://github.com/timkpaine/jupyterlab_commands
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Arbitrary python commands for notebooks in JupyterLab

  description: |
    Arbitrary python commands for notebooks in JupyterLab
  dev_url: https://github.com/timkpaine/jupyterlab_commands

extra:
  recipe-maintainers:
    - timkpaine
